### ISSUE TITLE
Add CSS & SCSS linting

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-plugin-boilerplate#123]
https://packagecontrol.io/packages/SublimeLinter-contrib-scss-lint

http://clubmate.fi/how-to-configure-sublimelinter/

**Comment by dotherightthing** [comment]
https://github.com/attenzione/SublimeLinter-scss-lint

SublimeLinter-contrib-scss-lint

```
.scss-lint.yml

# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: false

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: false

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 7
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: false

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertySortOrder:
    order:
      - position
      - top
      - right
      - bottom
      - left
      - z-index

      - display
      - box-sizing
      - content
      - align-content
      - align-items
      - align-self
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - justify-content
      - order
      - float
      - clear
      - vertical-align
      - width
      - height
      - max-width
      - max-height
      - min-width
      - min-height

      - overflow
      - overflow-x
      - overflow-y

      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left

      - border
      - border-collapse
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-color
      - border-image
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      - border-spacing
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      - border-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - border-top-left-radius
      - border-radius-topright
      - border-radius-bottomright
      - border-radius-bottomleft
      - border-radius-topleft

      - outline
      - outline-style
      - outline-offset

      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - margin-collapse
      - margin-top-collapse
      - margin-right-collapse
      - margin-bottom-collapse
      - margin-left-collapse

      - background
      - background-attachment
      - background-image
      - background-repeat
      - background-position
      - background-size
      - background-color
      - background-clip
      - clip

      - font
      - font-family
      - font-size
      - line-height
      - font-weight
      - font-style
      - color
      - font-smoothing
      - osx-font-smoothing

      - text-align
      - text-decoration
      - text-indent
      - text-overflow
      - text-rendering
      - text-size-adjust
      - text-shadow
      - text-transform
      - word-spacing
      - word-break
      - word-wrap
      - letter-spacing
      - white-space
      - direction
      - speak

      - list-style
      - list-style-type
      - list-style-position
      - list-style-image

      - visibility
      - opacity

      - transform

      - box-shadow

      - filter

      - animation
      - animation-delay
      - animation-duration
      - animation-iteration-count
      - animation-name
      - animation-play-state
      - animation-timing-function
      - animation-fill-mode

      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function

      - pointer-events
      - cursor
      - user-select

      - hyphens
      - src
      - quotes
      - size
      - zoom
      - box-align
      - box-flex
      - box-orient
      - box-pack

      - table-layout
      - backface-visibility
      - resize
      - appearance
      - interpolation-mode
      - marks
      - page
      - set-link-source
      - unicode-bidi
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false

  PropertySpelling:
    enabled: true
    extra_properties: []

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 6

  SelectorFormat:
    enabled: false
    convention: hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'no_space'

  SpaceBeforeBrace:
    enabled: false
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: false

  TransitionAll:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: bourbon
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
```
